server {
  listen 80;
  server_name producaovemexhidraulica.tech;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name producaovemexhidraulica.tech;
  ssl_certificate /etc/letsencrypt/live/producaovemexhidraulica.tech/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/producaovemexhidraulica.tech/privkey.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html =404;
  }
}